using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ApiTemplate.SourceGenerators
{
    [Generator]
    public class DynamicApiGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 找到所有带有 [DynamicApi] 特性的接口
            var provider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (s, _) => s is InterfaceDeclarationSyntax ids && ids.AttributeLists.Count > 0,
                    transform: (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(m => m != null);

            context.RegisterSourceOutput(provider, (spc, source) => Execute(spc, source));
        }

        private INamedTypeSymbol GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var interfaceDeclaration = (InterfaceDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(interfaceDeclaration) as INamedTypeSymbol;
            if (symbol == null) return null;

            foreach (var attribute in symbol.GetAttributes())
            {
                if (attribute.AttributeClass?.Name == "DynamicApiAttribute" ||
                    attribute.AttributeClass?.Name == "DynamicApi")
                {
                    return symbol;
                }
            }
            return null;
        }

        private void Execute(SourceProductionContext context, INamedTypeSymbol symbol)
        {
            var namespaceName = symbol.ContainingNamespace.ToDisplayString();
            var interfaceName = symbol.Name;
            var controllerName = interfaceName;
            
            // 去掉 I 前缀，去掉 Service 后缀，加上 Controller 后缀
            if (controllerName.StartsWith("I")) controllerName = controllerName.Substring(1);
            if (controllerName.EndsWith("Service")) controllerName = controllerName.Substring(0, controllerName.Length - 7);
            controllerName += "Controller";

            var sourceBuilder = new StringBuilder();
            sourceBuilder.AppendLine("// <auto-generated/>");
            sourceBuilder.AppendLine("using Microsoft.AspNetCore.Mvc;");
            sourceBuilder.AppendLine("using System.Threading.Tasks;");
            sourceBuilder.AppendLine($"using {namespaceName};");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("namespace ApiTemplate.Controllers");
            sourceBuilder.AppendLine("{");
            sourceBuilder.AppendLine("    [ApiController]");
            sourceBuilder.AppendLine($"    [Route(\"api/[controller]\")]");
            sourceBuilder.AppendLine($"    public class {controllerName} : ControllerBase");
            sourceBuilder.AppendLine("    {");
            sourceBuilder.AppendLine($"        private readonly {interfaceName} _service;");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine($"        public {controllerName}({interfaceName} service)");
            sourceBuilder.AppendLine("        {");
            sourceBuilder.AppendLine("            _service = service;");
            sourceBuilder.AppendLine("        }");

            foreach (var member in symbol.GetMembers().OfType<IMethodSymbol>())
            {
                if (member.MethodKind != MethodKind.Ordinary) continue;

                var methodName = member.Name;
                var returnType = member.ReturnType.ToDisplayString();
                
                // 处理参数
                var parameters = string.Join(", ", member.Parameters.Select(p => $"{p.Type.ToDisplayString()} {p.Name}"));
                var args = string.Join(", ", member.Parameters.Select(p => p.Name));

                // 根据方法名推断 HTTP 方法
                var httpMethod = "HttpPost";
                var lowerMethodName = methodName.ToLower();
                if (lowerMethodName.StartsWith("get") || lowerMethodName.StartsWith("query") || lowerMethodName.StartsWith("find")) 
                    httpMethod = "HttpGet";
                else if (lowerMethodName.StartsWith("update") || lowerMethodName.StartsWith("edit") || lowerMethodName.StartsWith("modify")) 
                    httpMethod = "HttpPut";
                else if (lowerMethodName.StartsWith("delete") || lowerMethodName.StartsWith("remove")) 
                    httpMethod = "HttpDelete";

                sourceBuilder.AppendLine();
                sourceBuilder.AppendLine($"        [{httpMethod}(\"{methodName}\")]");
                sourceBuilder.AppendLine($"        public {returnType} {methodName}({parameters})");
                sourceBuilder.AppendLine("        {");
                if (returnType != "void" && returnType != "System.Threading.Tasks.Task")
                {
                    sourceBuilder.AppendLine($"            return _service.{methodName}({args});");
                }
                else
                {
                    sourceBuilder.AppendLine($"            _service.{methodName}({args});");
                }
                sourceBuilder.AppendLine("        }");
            }

            sourceBuilder.AppendLine("    }");
            sourceBuilder.AppendLine("}");

            context.AddSource($"{controllerName}.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
        }
    }
}
