using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ApiTemplate.SourceGenerators
{
    [Generator]
    public class DynamicApiControllerGenerator : IIncrementalGenerator
    {
        private const string AttributeName = "ApiTemplate.Infrastructure.DynamicApi.DynamicApiAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 找到所有标记了特定特性的接口或类
            IncrementalValuesProvider<INamedTypeSymbol> declarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is null == false)!;

            // 生成代码
            context.RegisterSourceOutput(declarations, static (spc, source) => Execute(spc, source));
        }

        private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
        {
            // 检查是否是接口声明或类声明
            if (node is TypeDeclarationSyntax typeDecl && (node.IsKind(SyntaxKind.ClassDeclaration) || node.IsKind(SyntaxKind.InterfaceDeclaration)))
            {
                // 检查是否有任何特性
                return typeDecl.AttributeLists.Count > 0;
            }
            return false;
        }

        private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var typeDeclaration = (TypeDeclarationSyntax)context.Node;

            foreach (AttributeListSyntax attributeListSyntax in typeDeclaration.AttributeLists)
            {
                foreach (AttributeSyntax attributeSyntax in attributeListSyntax.Attributes)
                {
                    // 简化判断：只要特性名字包含 DynamicApi 就认为是目标，避免由于程序集引用隔离导致符号解析失败
                    string attrName = attributeSyntax.Name.ToString();
                    if (attrName.Contains("DynamicApi"))
                    {
                        return context.SemanticModel.GetDeclaredSymbol(typeDeclaration) as INamedTypeSymbol;
                    }
                }
            }

            return null;
        }

        private static void Execute(SourceProductionContext context, INamedTypeSymbol typeSymbol)
        {
            // 分析目标类型并生成控制器代码
            string namespaceName = "ApiTemplate.Controllers.Generated";
            
            // 如果是接口，去掉开头的 'I'
            string serviceName = typeSymbol.Name;
            if (typeSymbol.TypeKind == TypeKind.Interface && serviceName.StartsWith("I") && serviceName.Length > 1 && char.IsUpper(serviceName[1]))
            {
                serviceName = serviceName.Substring(1);
            }
            
            string controllerName = serviceName;
            if (!controllerName.EndsWith("Controller"))
            {
                if (controllerName.EndsWith("Service"))
                {
                    controllerName = controllerName.Substring(0, controllerName.Length - 7) + "Controller";
                }
                else
                {
                    controllerName += "Controller";
                }
            }

            // 获取路由前缀，如果有的话
            string routePrefix = $"api/{controllerName.Replace("Controller", "").ToLower()}";
            var attrData = typeSymbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name.Contains("DynamicApi") == true);
            if (attrData != null && attrData.ConstructorArguments.Length > 0 && attrData.ConstructorArguments[0].Value is string customRoute)
            {
                routePrefix = customRoute;
            }

            StringBuilder sourceBuilder = new StringBuilder($@"
// <auto-generated/>
#nullable enable
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using {typeSymbol.ContainingNamespace.ToDisplayString()};

namespace {namespaceName}
{{
    [ApiController]
    [Route(""{routePrefix}"")]
    public class {controllerName} : ControllerBase
    {{
        private readonly {typeSymbol.ToDisplayString()} _service;

        public {controllerName}({typeSymbol.ToDisplayString()} service)
        {{
            _service = service;
        }}
");

            // 遍历所有公共方法
            var members = typeSymbol.GetMembers().OfType<IMethodSymbol>().Where(m => m.MethodKind == MethodKind.Ordinary);
            
            foreach (var method in members)
            {
                GenerateMethod(sourceBuilder, method);
            }

            sourceBuilder.Append(@"    }
}");

            context.AddSource($"{controllerName}.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
        }

        private static void GenerateMethod(StringBuilder sourceBuilder, IMethodSymbol method)
        {
            string methodName = method.Name;
            string asyncSuffix = methodName.EndsWith("Async") ? "" : "";
            
            // 确定 HTTP 动词
            string httpMethod = GetHttpMethod(methodName);
            string returnType = method.ReturnType.ToDisplayString();
            
            // 确定是否需要 await
            bool isAsync = returnType.StartsWith("System.Threading.Tasks.Task");
            string awaitPrefix = isAsync ? "await " : "";

            sourceBuilder.Append($@"
        [Http{httpMethod}(""{methodName.Replace("Async", "")}"")]
        public async Task<IActionResult> {methodName}(");

            // 处理参数
            List<string> parameters = new List<string>();
            List<string> args = new List<string>();
            
            foreach (var param in method.Parameters)
            {
                string paramType = param.Type.ToDisplayString();
                string paramName = param.Name;
                
                // 简单类型使用 FromQuery，复杂类型使用 FromBody
                string binding = IsPrimitive(param.Type) ? "[FromQuery] " : "[FromBody] ";
                
                // 如果是 GET 请求且有复杂类型参数，这里简化处理，全部放 body 可能会报错，但标准做法是 GET 不用 Body
                if (httpMethod == "Get" && !IsPrimitive(param.Type))
                {
                    binding = "[FromQuery] "; // 强制转为 Query 尽量避免 GET 报 415
                }

                parameters.Add($"{binding}{paramType} {paramName}");
                args.Add(paramName);
            }

            sourceBuilder.Append(string.Join(", ", parameters));
            sourceBuilder.Append(@")
        {
");

            // 调用服务方法
            string callCode = $"{awaitPrefix}_service.{methodName}({string.Join(", ", args)})";
            
            if (returnType == "void" || returnType == "System.Threading.Tasks.Task")
            {
                sourceBuilder.Append($@"            {callCode};
            return Ok();");
            }
            else
            {
                sourceBuilder.Append($@"            var result = {callCode};
            return Ok(result);");
            }

            sourceBuilder.Append(@"
        }
");
        }

        private static string GetHttpMethod(string methodName)
        {
            var lowerName = methodName.ToLowerInvariant();
            if (lowerName.StartsWith("get") || lowerName.StartsWith("find") || lowerName.StartsWith("query") || lowerName.StartsWith("search"))
                return "Get";
            if (lowerName.StartsWith("update") || lowerName.StartsWith("edit") || lowerName.StartsWith("modify"))
                return "Put";
            if (lowerName.StartsWith("delete") || lowerName.StartsWith("remove"))
                return "Delete";
            
            return "Post";
        }

        private static bool IsPrimitive(ITypeSymbol typeSymbol)
        {
            switch (typeSymbol.SpecialType)
            {
                case SpecialType.System_Boolean:
                case SpecialType.System_Byte:
                case SpecialType.System_Char:
                case SpecialType.System_DateTime:
                case SpecialType.System_Decimal:
                case SpecialType.System_Double:
                case SpecialType.System_Int16:
                case SpecialType.System_Int32:
                case SpecialType.System_Int64:
                case SpecialType.System_SByte:
                case SpecialType.System_Single:
                case SpecialType.System_String:
                case SpecialType.System_UInt16:
                case SpecialType.System_UInt32:
                case SpecialType.System_UInt64:
                    return true;
            }
            
            if (typeSymbol.TypeKind == TypeKind.Enum)
                return true;
                
            if (typeSymbol.ToDisplayString() == "System.Guid")
                return true;

            return false;
        }
    }
}