// ApiSourceGenerator/DynamicApiControllerGenerator.cs
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

[Generator]
public class DynamicApiControllerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var declarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is InterfaceDeclarationSyntax i
                                            && i.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetTarget(ctx))
            .Where(static (INamedTypeSymbol? m) => m is not null)!;

        context.RegisterSourceOutput(declarations, Execute);
    }

    private static INamedTypeSymbol? GetTarget(GeneratorSyntaxContext context)
    {
        var interfaceDecl = (InterfaceDeclarationSyntax)context.Node;
        foreach (var attrList in interfaceDecl.AttributeLists)
            foreach (var attr in attrList.Attributes)
            {
                if (attr.Name.ToString().Contains("DynamicApi"))
                    return context.SemanticModel.GetDeclaredSymbol(interfaceDecl) as INamedTypeSymbol;
            }
        return null;
    }

    private static void Execute(SourceProductionContext context, INamedTypeSymbol ifaceSymbol)
    {
        // 1. 推断 Controller 名和路由
        string ifaceName = ifaceSymbol.Name; // IUserService
        string serviceName = ifaceName.StartsWith("I") && ifaceName.Length > 1 && char.IsUpper(ifaceName[1])
            ? ifaceName.Substring(1)         // UserService
            : ifaceName;

        // UserService → User → UserController
        string baseName = serviceName.EndsWith("Service")
            ? serviceName.Substring(0, serviceName.Length - 7)
            : serviceName;
        string controllerName = baseName + "Controller";

        // 路由：优先用 [DynamicApi("...")] 参数，否则 api/user
        string routePrefix = $"api/{baseName.ToLower()}";
        var dynAttr = ifaceSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name.Contains("DynamicApi") == true);
        if (dynAttr?.ConstructorArguments.Length > 0
            && dynAttr.ConstructorArguments[0].Value is string customRoute
            && !string.IsNullOrEmpty(customRoute))
        {
            routePrefix = customRoute;
        }

        // 2. 收集需要生成的方法
        var methods = ifaceSymbol.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m.GetAttributes()
                .Any(a => a.AttributeClass?.Name.Contains("ApiAction") == true))
            .ToList();

        if (methods.Count == 0) return;

        // 3. 拼代码
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using Microsoft.AspNetCore.Authorization;");
        sb.AppendLine($"using {ifaceSymbol.ContainingNamespace.ToDisplayString()};");
        sb.AppendLine();
        sb.AppendLine("namespace ApiTemplate.Controllers.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    [ApiController]");
        sb.AppendLine($"    [Route(\"{routePrefix}\")]");
        sb.AppendLine($"    public class {controllerName} : ControllerBase");
        sb.AppendLine("    {");
        sb.AppendLine($"        private readonly {ifaceSymbol.ToDisplayString()} _service;");
        sb.AppendLine();
        sb.AppendLine($"        public {controllerName}({ifaceSymbol.ToDisplayString()} service)");
        sb.AppendLine("        {");
        sb.AppendLine("            _service = service;");
        sb.AppendLine("        }");

        foreach (var method in methods)
        {
            GenerateAction(sb, method);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{controllerName}.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateAction(StringBuilder sb, IMethodSymbol method)
    {
        // 1. 读 [ApiAction(httpMethod, route)]
        var actionAttr = method.GetAttributes()
            .First(a => a.AttributeClass?.Name.Contains("ApiAction") == true);

        string httpMethod = actionAttr.ConstructorArguments[0].Value?.ToString() ?? "POST";
        string route = actionAttr.ConstructorArguments[1].Value?.ToString() ?? "";

        // 2. 透传其他 Attribute（排除 ApiAction 本身）
        //    只透传白名单内的，避免透传编译器/语言层面的 Attribute
        var passthroughAttrs = method.GetAttributes()
            .Where(a => ShouldPassThrough(a.AttributeClass?.ToDisplayString()))
            .ToList();

        // 3. 处理参数
        var parameters = new List<string>();
        var arguments = new List<string>();
        foreach (var param in method.Parameters)
        {
            // 保留用户在接口方法上写的 [FromBody] [FromQuery] 等
            string attrs = string.Join(" ", param.GetAttributes()
                .Select(a => $"[{a.AttributeClass?.Name}]"));
            string prefix = attrs.Length > 0 ? attrs + " " : "";
            parameters.Add($"{prefix}{param.Type.ToDisplayString()} {param.Name}");
            arguments.Add(param.Name);
        }

        // 4. 返回类型处理：保留原始返回类型（保留 Swagger 可见性）
        string returnType = method.ReturnType.ToDisplayString();
        bool isVoidTask = returnType == "System.Threading.Tasks.Task" || returnType == "void";
        bool isAsync = returnType.StartsWith("System.Threading.Tasks.Task") || returnType == "System.Threading.Tasks.Task";
        string asyncKeyword = isAsync ? "async " : "";
        string awaitKeyword = isAsync ? "await " : "";

        // Action 返回类型：void/Task → IActionResult / Task<IActionResult>，其他保持
        string actionReturn = isVoidTask
            ? (isAsync ? "Task<IActionResult>" : "IActionResult")
            : returnType;            // e.g. Task<UserDto> or string

        // 方法名去掉 Async 后缀作为 Action 名
        string actionName = method.Name.EndsWith("Async")
            ? method.Name.Substring(0, method.Name.Length - 5)
            : method.Name;

        sb.AppendLine();

        // 透传的 Attribute
        foreach (var attr in passthroughAttrs)
        {
            // 取原始语法文本，原样输出
            var syntaxRef = attr.ApplicationSyntaxReference;
            if (syntaxRef != null)
            {
                string attrText = syntaxRef.GetSyntax().ToFullString().Trim();
                sb.AppendLine($"        [{attrText}]");
            }
        }

        sb.AppendLine($"        [Http{ToTitleCase(httpMethod)}(\"{route}\")]");
        sb.AppendLine($"        public {asyncKeyword}{actionReturn} {actionName}({string.Join(", ", parameters)})");
        sb.AppendLine("        {");

        string callExpr = $"{awaitKeyword}_service.{method.Name}({string.Join(", ", arguments)})";

        if (isVoidTask)
        {
            sb.AppendLine($"            {callExpr};");
            sb.AppendLine("            return Ok();");
        }
        else
        {
            sb.AppendLine($"            return {callExpr};");  // 直接 return，保留类型
        }

        sb.AppendLine("        }");
    }

    // 白名单：只透传这些 Attribute 到生成的 Action
    private static bool ShouldPassThrough(string? fullName)
    {
        if (fullName is null) return false;
        return fullName.StartsWith("Microsoft.AspNetCore.Authorization") // Authorize, AllowAnonymous
            || fullName.StartsWith("Microsoft.AspNetCore.Mvc.Produces")  // ProducesResponseType
            || fullName.StartsWith("Microsoft.AspNetCore.RateLimiting")  // EnableRateLimiting
            || fullName.StartsWith("Microsoft.AspNetCore.OutputCaching"); // OutputCache
    }

    private static string ToTitleCase(string s) =>
        string.IsNullOrEmpty(s) ? s : char.ToUpper(s[0]) + s.Substring(1).ToLower();
}